### ISSUE TITLE
Collect Twitter mentions of the specific topic: fraud, negative sentiment - 25$

### ISSUE THREAD

**Issue by PolinaPanicheva** [inca-digital/bounty#50]
The goal for this issue is to collect a minimum of 200 tweets in response to the frauds at crypto custodians (you can find one of the exchanges lists here https://www.cointelligence.com/exchanges_list/. A good example of a fraud event we are interested in is [Africrypt affair](https://www.forbes.com/sites/emilymason/2021/06/23/south-african-brothers-disappear-along-with-22-billion-worth-of-bitcoin/). More fraud examples can be found in this file https://drive.google.com/file/d/1eWpuIpAXZGx4x-lHvkmUbrZ7GvjBymXx/view?usp=sharing).

A suggested way to deal with the issue is the following:

- Find relevant to the topic events - exit scams, insider jobs, etc. - anything that signals fraud problems. You may use Google News for this (the search query could be ${Exchange Name} + ${Topic}). Example: “Africrypt exit scam”
- Use the search results to figure the dates of the event (example: suppose there is news on Africrypt on June 23)
- Filter Twitter results by date close to the event
- For this issue, look for the tweets, negatively commenting on the fraud problems of custody-providers services.
- If you think the Tweet is relevant, add this to a CSV, using the following format: “username, date, tweet-content, topic”
- To better understand if the Tweet addresses the necessary topic, you can find examples of the fraud-related tweets here https://docs.google.com/spreadsheets/d/1odWHLPDl5Kg99uwc7ngRJzrD2ZKT3TVnXkvwte_jDlw/edit?usp=sharing.

Important note:

- **Do not Twitter-search for the topic-related keywords**, such as “fraud” - instead, make sure to follow the steps described above. With that, filter Twitter search by dates and custodian names only. (Example: search for “Africrypt”, June 22-24 because the news about the scam went out on June 23)

Feel free to **ask questions** by commenting the issue below.

To **start the task**:

- Leave a comment in this GitHub issue.
- In the comment, let us know you’ve started the task and mention the amount of time you will need to finish it.
- Submit your results in a .csv file to bounty@inca.digital. Make sure to indicate your preferred payment method.

**Comment by piksida** [comment]
need around a week

**Comment by valerikache** [comment]
привет! я беру это задачу. примерно 3 дня. несколько вопросов:
1) учитывать ли репосты твитов?
2) только английский текст твитов?
3) близко по дате события, это 2-3 дня или можно больше?
4) дата это только день месяц год или еще время твита тоже?

**Comment by valerikache** [comment]
Hey! I take this task. about 3 days. a few questions:
1) should tweet reposts be considered?
2) only English text of tweets?
3) close to the date of the event, is it 2-3 days or more?
4) is the date only day month year or tweet time too?

**Comment by PolinaPanicheva** [comment]
> Hey! I take this task. about 3 days. a few questions:
> 1) should tweet reposts be considered?

Yes, if the reposts themselves are meaningful and relevant (not just a repost with empty text).
> 2) only English text of tweets?

Yes.
> 3) close to the date of the event, is it 2-3 days or more?

Whatever works for you to find the relevant tweets. 2-3 days after the event is just a suggested starting point.
> 4) is the date only day month year or tweet time too?

Tweet time is optional, but make the date format uniform throughout your file.

**Comment by Irina-Na** [comment]
It will be done by July 11

**Comment by Irina-Na** [comment]
> 
> 
> It will be done by July 11

Update will be done by July  19

**Comment by Irina-Na** [comment]
Ready
