### ISSUE TITLE
Collect Twitter mentions of the specific topic: hacker attack, negative sentiment - 25$

### ISSUE THREAD

**Issue by PolinaPanicheva** [inca-digital/bounty#56]
**The goal for this issue is to collect a minimum of 200 tweets related to hacker attacks at crypto custodians**
(you can find one of the exchanges lists [here](https://www.cointelligence.com/exchanges_list/), and examples of the events that are of our interest [in this file](https://drive.google.com/file/d/1BjbGFAG_Z-P9Gw13M6lg9zNaYOmZ7Fdc/view?usp=sharing)). 

### A suggested way to deal with the issue is the following:
1.  Find relevant to the topic events - ddos, hacks, stolen funds, etc. - anything that relates to hacker attacks and security breaches at crypto custodians.
You may use Google News for this (the search query could be ${Exchange Name} + ${Topic}). Example: “binance stolen funds”
2.  Use the search results to figure the dates of the event (example: the hacker attack happened on Nov 26th)
3.  Filter Twitter results by date close to the event
4.  For this issue, look for the tweets, negatively commenting on the hacker attack, security breach or stolen funds at custody-providers services (example: "If you have coins in {Exchange Name} you have just lost it all").
5.  If you think the Tweet is relevant, add this to a CSV, using the following format:
“username, date, tweet-content, topic” 

To better understand if the Tweet addresses the necessary topic, you can find examples of the hacker attack-related tweets [here](https://docs.google.com/spreadsheets/d/1qMPHyTeyQy_9x6BpNblGhclcjGoEStsKRiUNrfiJCCU/edit?usp=sharing)

**Important note:**

  Do not Twitter-search for the topic-related keywords, such as “attack” - instead, make sure to follow the steps, as described above. With that, filter Twitter search by dates and Exchange names only. (Example: search for “binance”, Nov 26-28 because the attack happened on Nov 26).

Feel free to **ask questions** by commenting the issue below and **take a look** at the issues on other topics in [this folder](https://github.com/1712n/bounty/issues).

**To start the task:**
1.  Leave a comment in this GitHub issue.
2.  In the comment, let us know you’ve started the task and mention the amount of time you will need to finish it.

**Upon completion of the task:**
1.  Upload your CSV file to Google Drive and share it with bounty@incasec.com
2.  Leave a comment in the issue, saying you’re done
3.  Send an email to bounty@incasec.com with the info on the preferable payment method

**Comment by fortunerus** [comment]
Hi! i'm starting job. I need 5 days

**Comment by fortunerus** [comment]
“username, date, tweet-content, topic” - what does "topic" mean?

**Comment by PolinaPanicheva** [comment]
> “username, date, tweet-content, topic” - what does "topic" mean?

the topic is "hacker attack" in this issue, and the respective topic for other issues ("support" for the [other issue](https://github.com/1712n/bounty/issues/54) you've taken).

**Comment by Irina-Na** [comment]
I take this task.  It'll be ready by July 21 or 28

**Comment by Irina-Na** [comment]
In [examples](https://docs.google.com/spreadsheets/d/1qMPHyTeyQy_9x6BpNblGhclcjGoEStsKRiUNrfiJCCU/edit#gid=0) I found tweet: `#Binance has been hacked 💀 $BNB Quoted tweet from @cz_binance: Not the best of days, but we will stay transparent. Thank you for your support! binance.zendesk.com/hc/en-us/artic…` with not ended content. Do we need to use Twitter API or just web-search and copy/paste for data collection?

**Comment by Irina-Na** [comment]
3. What type of date format we need to use?

**Comment by PolinaPanicheva** [comment]
> In [examples](https://docs.google.com/spreadsheets/d/1qMPHyTeyQy_9x6BpNblGhclcjGoEStsKRiUNrfiJCCU/edit#gid=0) I found tweet: `#Binance has been hacked 💀 $BNB Quoted tweet from @cz_binance: Not the best of days, but we will stay transparent. Thank you for your support! binance.zendesk.com/hc/en-us/artic…` with not ended content.   
Probably the tweet text is not full because it's a retweet. It's ok if retweets are not full-text in your examples. In this case it's better to include the original tweet in full, too, if it is relevant for the topic.
> 1. Do we need to use Twitter API or just web-search and copy/paste for data collection? 
Use whatever works to collect relevant examples. If you use the API, make sure to check the arguments to obtain the text as full as you can (_tweet_mode='extended'_)
> 2. What to do with a long HTTP address?
Not too important. It's ok if it's shown as full as it can be (see my answers above).

**Comment by PolinaPanicheva** [comment]
> 3. What type of date format we need to use?

Doesn't really matter, but make it the same format throughout your file.

**Comment by Irina-Na** [comment]
Done

**Comment by valerikache** [comment]
Hi! I take this task. about 2 days.

**Comment by valerikache** [comment]
Done
